name: login
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.12.2
  firebase_storage: ^11.4.1
  firebase_auth: ^4.12.1
  youtube_player_flutter: ^8.1.2
  flutter_rating_bar: ^4.0.1
  video_player: ^2.6.1
  table_calendar: ^3.0.9
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.1
  url_launcher: ^6.0.0
  lottie: ^2.6.0
  concentric_transition: ^1.0.3
  day_night_switcher: ^0.2.0+1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  uni_links: ^0.5.1
  firebase_core: ^2.21.0
  google_maps_flutter: ^2.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/.
    - assets/.
    - assets/animation/.
